import http from "node:http";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const port = Number(process.env.PORT || 3000);
const maxSpend = Number(process.env.MAX_AI_SPEND_USD || 1);
let aiSpent = 0;
const crmLeads = [];
const mail = [];
const notifications = [];
const events = [];
function requestIp(req) { return (req.headers["x-forwarded-for"] || req.socket.remoteAddress || "0.0.0.0").split(",")[0].trim(); }
function maskIp(ip) { const parts=ip.replace("::ffff:","").split("."); return parts.length===4 ? `${parts[0]}.${parts[1]}.x.x` : "masked"; }
function demoRegion(ip, username="") { const hint=username.toLowerCase(); if(hint.includes("eu")) return "EU"; if(hint.includes("us")) return "US"; const last=Number(ip.split(".").pop()); return Number.isFinite(last)&&last%2===0 ? "EU" : "US"; }
function classify(e) { const evidence=[]; let score=20; if(e.pages.includes("/pricing")){score+=35;evidence.push("Viewed pricing")} if(e.pages.includes("/integrations")){score+=25;evidence.push("Viewed integrations")} if(e.visits>1){score+=15;evidence.push("Returned visitor")} if(e.minutes>=5){score+=10;evidence.push("Meaningful time on site")} if(e.region)evidence.push(`Coarse region ${e.region}`); const level=score>=70?"high":score>=45?"medium":"low"; return {...e,score,level,evidence,recommendation:e.region==="EU"?"EU privacy review · email held for approval":level==="high"?"Create or update CRM lead and notify sales":"Keep monitoring"}; }
async function processEvent(e) { const result=classify(e); if(process.env.AI_MODE==="live"&&process.env.OPENROUTER_API_KEY&&aiSpent+0.01<=maxSpend){const response=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENROUTER_MODEL||"openai/gpt-4o-mini",max_tokens:120,temperature:0,messages:[{role:"system",content:"Return JSON only with keys level and recommendation. level must be high, medium, or low."},{role:"user",content:JSON.stringify({pages:e.pages,minutes:e.minutes,visits:e.visits})}]})}); if(response.ok){const body=await response.json();try{const ai=JSON.parse(body.choices?.[0]?.message?.content||"{}");if(["high","medium","low"].includes(ai.level))result.level=ai.level;if(ai.recommendation)result.recommendation=ai.recommendation;aiSpent+=0.01;}catch{result.aiNote="OpenRouter response was not valid JSON; rules retained";}}} const existing=crmLeads.find(l=>l.email===e.email); result.crm=existing?"updated existing mock Salesforce lead":"created mock Salesforce lead"; result.route=e.region==="EU"?"EU privacy review · email held for approval":"US sales route · Slack + email"; if(existing) Object.assign(existing,result); else crmLeads.push(result); if(result.level==="high"){const message=`High-intent ${e.region||"US"} visitor: ${e.company} (${e.email}) scored ${result.score}. Evidence: ${result.evidence.join(", ")}.`; if(e.region!=="EU"){notifications.unshift({channel:"mock Slack",message,at:new Date().toISOString()});mail.unshift({to:"sales@example.test",subject:`New high-intent lead: ${e.company}`,body:message,at:new Date().toISOString()});}else{mail.unshift({to:"privacy-review@example.test",subject:`EU lead awaiting approval: ${e.company}`,body:`Review before sales outreach. ${message}`,at:new Date().toISOString()});}} return result; }
function json(res,status,body){res.writeHead(status,{"content-type":"application/json"});res.end(JSON.stringify(body));}
const server=http.createServer(async(req,res)=>{ if(req.url==="/api/events") return json(res,200,{events:events.map(classify),crmLeads,mail,notifications,aiMode:process.env.AI_MODE||"mock",salesforceMode:process.env.SALESFORCE_MODE||"mock",maxSpend,aiSpent}); if(req.method==="POST"&&req.url==="/api/login"){let raw="";for await(const c of req)raw+=c;const input=JSON.parse(raw||"{}");const ip=requestIp(req);const region=demoRegion(ip,input.username);const e={id:`evt-${Date.now()}`,email:input.username+"@demo.test",company:"Demo Visitor",pages:["/pricing","/integrations"],minutes:7,visits:2,trigger:"generic login",ip:maskIp(ip),region};events.unshift(e);return json(res,200,{event:await processEvent(e),visitor:{ip:e.ip,region},triggered:region==="EU"?["mock Salesforce", "EU privacy review email", "n8n webhook-ready event"]:["mock Salesforce", "mock email", "mock Slack notification", "n8n webhook-ready event"]});} if(req.method==="POST"&&req.url==="/api/track"){let raw="";for await(const c of req)raw+=c;const input=JSON.parse(raw||"{}");const ip=requestIp(req);const e={...input,id:`evt-${Date.now()}`,ip:maskIp(ip),region:demoRegion(ip,input.username||input.email||"")};events.unshift(e);return json(res,200,{event:await processEvent(e),visitor:{ip:e.ip,region:e.region},duplicateProtection:"matching emails update the mock Salesforce lead instead of creating another",aiSpendGuard:`local cap $${maxSpend.toFixed(2)}`});} const file=join(root,"public",req.url==="/"?"index.html":req.url); try{const body=await readFile(file);res.writeHead(200,{"content-type":file.endsWith(".css")?"text/css":file.endsWith(".js")?"text/javascript":"text/html"});res.end(body);}catch{json(res,404,{error:"Not found"})} });
let deliveredMail=0;
async function deliverToMailpit(message) { if(process.env.MAILPIT_ENABLED!=="true") return true; const base=process.env.MAILPIT_URL||"http://localhost:8025"; try{const response=await fetch(`${base}/api/v1/send`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({From:{Email:"demo@buying-signal.local",Name:"Buying Signal Demo"},To:[{Email:message.to}],Subject:message.subject,Text:message.body})});return response.ok;}catch(error){console.warn("Mailpit delivery skipped:",error.message);return false;} }
setInterval(async()=>{if(deliveredMail<mail.length&&await deliverToMailpit(mail[deliveredMail]))deliveredMail++;},250);
server.listen(port,()=>console.log(`demo listening on ${port}`));
